### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by acao** [acao/geoblaze-gsoc#2]
democratizing access to geospatial tools and knowledge is my passion!

- [x] basic raster computation of GSOCMap for polygons/multipolygons
- [x] validate and normalize GeoJSON, allowing more geometry types - `LineString` and `MultiLineString`
- [x] add simple status area for steps/errors 
- [x] codemirror 6 JSON editor 😍
- [x] add 100 hectare limit until I can find out how to avoid proxying the geotiff/cheaper hosting
- [ ] dark mode
- [ ] upload GeoJSON files
- [ ] upload Shapefiles
- [ ] upload KML files
- [ ] drag and drop file upload
- [ ] map with `mapbox-gl-draw`
- [ ] support `FeatureCollection` 💸 
- [ ] optimize HTTP cacheing if possible
- [ ] workbox/similar for web cache API - offline doesn't make sense for geotiff
- [ ] build a codemirror mode for json schema validation/completion/etc and implement it using geojson spec
- [ ] perform a cost benefit analysis for self-hosting a copy of this file (and others) vs using verecel rewrites to circumvent cors same origin config
- [ ] add the rest of the FAO data for the various prediction scenarios
- [ ] author a blog post for software peeps
- [ ] author and submit an academic article

**Comment by Marcosmk12** [comment]
> democratizing access to geospatial tools and knowledge is my passion!
> 
> - [x] basic raster computation of GSOCMap for polygons/multipolygons
> - [x] validate and normalize GeoJSON, allowing more geometry types - `LineString` and `MultiLineString`
> - [x] add simple status area for steps/errors 
> - [x] codemirror 6 JSON editor 😍
> - [x] add 100 hectare limit until I can find out how to avoid proxying the geotiff/cheaper hosting
> - [ ] dark mode
> - [ ] upload GeoJSON files
> - [ ] upload Shapefiles
> - [ ] upload KML files
> - [ ] drag and drop file upload
> - [ ] map with `mapbox-gl-draw`
> - [ ] support `FeatureCollection` 💸 
> - [ ] optimize HTTP cacheing if possible
> - [ ] workbox/similar for web cache API - offline doesn't make sense for geotiff
> - [ ] build a codemirror mode for json schema validation/completion/etc and implement it using geojson spec
> - [ ] perform a cost benefit analysis for self-hosting a copy of this file (and others) vs using verecel rewrites to circumvent cors same origin config
> - [ ] add the rest of the FAO data for the various prediction scenarios
> - [ ] author a blog post for software peeps
> - [ ] author and submit an academic article
